Repository yjosp95/Project3, pull requests merged in 2020-06, with the labels that each got.

#5 Update Front-End (home.ejs) & Back-End (sellphone.js) For HomePage
  WebProject/routes/sellphone.js
  WebProject/views/home.ejs
Labels: development

#7 1. 자체 관리 로그인 구현 - pull request
  WebProject/routes/sellphone.js
  WebProject/views/login.ejs
Labels: development

#10 1. My page view 구현 - pull request
  WebProject/views/mypage.ejs
  WebProject/views/mypage_update.ejs
Labels: development

#12 2. My page DB연동 - pull reqeust
  WebProject/routes/sellphone.js
Labels: development

#14 3. My page DB연동 수정 - pull request
  WebProject/routes/sellphone.js
  WebProject/views/mypage.ejs
Labels: Modify

#16 상품 조회 및 등록입니다.
  WebProject/routes/sellphone.js
  WebProject/views/read.ejs
  WebProject/views/sell.ejs
Labels: development

#18 Page Intro
  WebProject/public/electro/css/style.css
  WebProject/public/electro/img/applelogo.png
  WebProject/public/electro/img/lglogo.png
  WebProject/public/electro/img/samsunglogo2.png
  WebProject/public/electro/img/telecom.jpg
  WebProject/routes/sellphone.js
  WebProject/views/intro.ejs
Labels: development

#19 2. 네이버 소셜 로그인 구현 - pull request
  WebProject/routes/sellphone.js
  WebProject/views/OK.ejs
Labels: development

#25 Hjh
  WebProject/routes/sellphone.js
  WebProject/views/read_update.ejs
Labels: development

#24 문의하기 기능 추가
  WebProject/routes/sellphone.js
  WebProject/views/ask.ejs
  WebProject/views/ask_list.ejs
  WebProject/views/ask_read.ejs
Labels: development

#29 공지사항 추가입니다
  WebProject/routes/sellphone.js
  WebProject/views/announcement.ejs
  WebProject/views/announcement_read.ejs
  WebProject/views/announcement_write.ejs
Labels: development

#30 4. My page 정보수정 동작 & 통계 그래프 구현 - pull request
  WebProject/routes/sellphone.js
  WebProject/views/mypage.ejs
  WebProject/views/mypage_update.ejs
Labels: development

#36 최종 구현 & 수정 완료
  WebProject/routes/sellphone.js
  WebProject/views/OK.ejs
  WebProject/views/charge.ejs
  WebProject/views/joinform.ejs
  WebProject/views/login.ejs
  WebProject/views/mypage.ejs
  WebProject/views/mypage_update.ejs
Labels: Modify, development

#37 Hjh
  WebProject/routes/sellphone.js
  WebProject/views/payment.ejs
Labels: development

#38 홈화면 로그인 기능 추가 및 링크 연결 업데이트
  WebProject/routes/sellphone.js
  WebProject/views/home.ejs
Labels: development

#39 검색 기능 & 정렬 기능 구현 업데이트
  WebProject/routes/sellphone.js
  WebProject/views/search.ejs
Labels: development

#41 Hjh
  WebProject/routes/sellphone.js
  WebProject/views/read_update.ejs
Labels: documentation

#42 상품별 Q&A, 조회수 카운팅, 찜 추가/제거 기능 구현
  WebProject/routes/sellphone.js
Labels: development

#45 회원 관리 페이지 구현
  WebProject/routes/sellphone.js
  WebProject/views/member_manage.ejs
Labels: development

#46 회원정보 페이지 구현입니다
  WebProject/routes/sellphone.js
  WebProject/views/member_mypage.ejs
Labels: development

#48 Update README.md
  README.md
Labels: documentation

#50 로그인 페이지 중 비밀번호 찾기
  WebProject/views/find_passwd.ejs
Labels: development

#51 리뷰 및 평점 시각화
  WebProject/routes/sellphone.js
Labels: development
